apiVersion: batch/v1
kind: CronJob
metadata:
  name: ys2wl
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 3
  jobTemplate:
    spec:
      backoffLimit: 0
      parallelism: 1
      template:
        spec:
          containers:
          - env:
            - name: TZ
              value: Europe/Oslo
            - name: OAUTHLIB_INSECURE_TRANSPORT
              value: "0"
            - name: CONFIG
              value: /opt/ys2wl/.ys2wl/config.yaml
            image: registry.hub.docker.com/bateau/ys2wl:latest
            imagePullPolicy: Always
            name: ys2wl
            volumeMounts:
            - mountPath: /opt/ys2wl/.ys2wl
              name: config
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          volumes:
          - hostPath:
              path: /home/<user>/.ys2wl
              type: ""
            name: config
      ttlSecondsAfterFinished: 162000
  schedule: 0 */10 * * *
  startingDeadlineSeconds: 360000
  successfulJobsHistoryLimit: 3
  suspend: false