apiVersion: v1
kind: ConfigMap
metadata:
  name: sortarr-config
data:
  SORTARR_API_PORT: "8080"
  SORTARR_COMPARE_DISTANCE: "97"
  SORTARR_CREDENTIALS_FILE: "/data/client_secret.json"
  SORTARR_DATABASE_FILE: "/data/my.db"
  SORTARR_LOG_FILE: "stream"
  SORTARR_LOG_LEVEL: "debug"
  SORTARR_MAXIMUM_LENGTH: "8m"
  SORTARR_MINIMUM_LENGTH: "75s"
  SORTARR_NO_WEBBROWSER: "true"
  SORTARR_PICKLE_FILE: "/data/credentials.pickle"
  SORTARR_PIPELINE_CONCURRENCY: "1"
  SORTARR_PLAYLIST_SLEEP: "30"
  SORTARR_REPROCESS_DAYS: "1"
  SORTARR_SCHEDULE: "0 */6 * * *"
  SORTARR_SUBSCRIPTION_SLEEP: "60"