apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sortarr
  namespace: seashell
  annotations:
    cert-manager.io/acme-challenge-type: http01
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: seashell-sortarr-auth@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
    - host: sortarr.bateau.cloud
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: sortarr
                port:
                  number: 8080
  tls:
    - hosts:
        - sortarr.bateau.cloud
      secretName: sortarr-tls