name: "Release build and push"

on:
  push:
    branches:
      - "main"

env:
  IMAGE_REGISTRY: registry.hub.docker.com
  IMAGE_REPOSITORY: bateau
  IMAGE_NAME: ys2wl
  GITHUB_REPO_NAME: plattform-workflow-dispatcher

permissions:
  contents: read

jobs:
  release:
    name: release
    uses: nrkno/github-workflow-semantic-release/.github/workflows/workflow.yaml@allways_output_version
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    with:
      runs-on: ubuntu-latest
      release-enabled: true
      lint-enabled: false
  build:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build_push.outputs.digest }}
    needs: release
    steps:
      - name: checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0
      - name: Checkout tag
        run: git checkout tags/${{ needs.release.outputs.release-version }}
      - uses: docker/login-action@v2.2.0
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.8.0
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v4.1.1
        with:
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true
          tags: |
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:${{ needs.release.outputs.release-version }}
            ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_REPOSITORY }}/${{ env.IMAGE_NAME }}:latest
